/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "primary": "#adc6ff",
        "surface-tint": "#adc6ff",
        "on-tertiary-container": "#eb4141",
        "on-primary-fixed": "#001a42",
        "on-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "on-primary": "#002e6a",
        "on-primary-fixed-variant": "#004395",
        "primary-fixed": "#d8e2ff",
        "surface-container-lowest": "#060e20",
        "surface-bright": "#31394d",
        "secondary": "#b7c8e1",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#930013",
        "surface-dim": "#0b1326",
        "tertiary": "#ffb3ad",
        "on-tertiary-fixed": "#410004",
        "on-secondary-container": "#a9bad3",
        "primary-container": "#00163a",
        "on-error-container": "#ffdad6",
        "surface-container": "#171f33",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-container-high": "#222a3d",
        "on-background": "#dae2fd",
        "on-secondary-fixed": "#0b1c30",
        "background": "#0b1326",
        "surface": "#0b1326",
        "on-secondary": "#213145",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-highest": "#2d3449",
        "secondary-container": "#3a4a5f",
        "on-tertiary": "#68000a",
        "error-container": "#93000a",
        "on-error": "#690005",
        "tertiary-fixed": "#ffdad7",
        "outline": "#909097",
        "tertiary-container": "#390003",
        "primary-fixed-dim": "#adc6ff",
        "inverse-primary": "#005ac2",
        "inverse-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "outline-variant": "#45464d",
        "secondary-fixed": "#d3e4fe",
        "on-primary-container": "#357df1",
        "surface-container-low": "#131b2e",
        "on-surface-variant": "#c6c6cd",
        "secondary-fixed-dim": "#b7c8e1",
        severity: {
          critical: '#ef4444',
          high: '#f97316',
          medium: '#f59e0b',
          low: '#10b981',
        },
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
